CREATE TABLE IF NOT EXISTS `visualizacao`.`trecho` (
  `idProcesso` VARCHAR(45) NULL DEFAULT NULL,
  `seqTrecho` VARCHAR(45) NULL DEFAULT NULL,
  `origemData` VARCHAR(45) NULL DEFAULT NULL,
  `origemPais` VARCHAR(45) NULL DEFAULT NULL,
  `origemUf` VARCHAR(45) NULL DEFAULT NULL,
  `origemCiade` VARCHAR(45) NULL DEFAULT NULL,
  `dataDestino` VARCHAR(45) NULL DEFAULT NULL,
  `DestinoPais` VARCHAR(45) NULL DEFAULT NULL,
  `estinoUf` VARCHAR(45) NULL DEFAULT NULL,
  `destinoCidade` VARCHAR(45) NULL DEFAULT NULL,
  `meioTransporte` VARCHAR(45) NULL DEFAULT NULL,
  `numeroDiarias` VARCHAR(45) NULL DEFAULT NULL,
  `missao` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
